### ISSUE TITLE
KeyError: 'bool'

### ISSUE THREAD

**Issue by harmtemolder** [kyxap/koreader-calibre-plugin#13]
@elmodor Did this new column of type `bool` (from #11) work for you? I get this error when running it in calibre (6.16):

```
Traceback (most recent call last):
  File "calibre_plugins.koreader.action", line 140, in show_config
    self.interface_action_base_plugin.do_user_config(self.gui)
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 156, in do_user_config
    config_widget = self.config_widget()
  File "calibre_plugins.koreader.__init__", line 48, in config_widget
    return ConfigWidget(self.actual_plugin_)
  File "calibre_plugins.koreader.config", line 209, in __init__
    custom_columns_layout = CustomColumnsLayout(self)
  File "calibre_plugins.koreader.config", line 296, in __init__
    available_columns[column['type']],
KeyError: 'bool'
```

**Comment by elmodor** [comment]
@harmtemolder please take a look at #14 

All should work now as expected.
