### ISSUE TITLE
AttributeError: 'list' object has no attribute 'values' when trying to sync

### ISSUE THREAD

**Issue by andreaschari** [kyxap/koreader-calibre-plugin#7]
I'm getting the following on `0.6.1`:

```
calibre, version 7.13.0
ERROR: Unhandled exception: <b>AttributeError</b>:'list' object has no attribute 'values'

calibre 7.13  embedded-python: True
Linux-6.5.0-41-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.5.0-41-generic', '#41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Annotations (1, 17, 13) && Goodreads (1, 8, 2) && KOReader Sync (0, 6, 1) && Kindle Comics Input (0, 0, 2) && Kindle Comics Output (0, 0, 2) && Kobo Utilities (2, 16, 13) && KoboTouchExtended (3, 6, 7) && Quality Check (1, 13, 11)
Traceback (most recent call last):
  File "calibre_plugins.koreader.action", line 768, in sync_to_calibre
    sidecar_contents = self.get_sidecar(device, sidecar_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.koreader.action", line 306, in get_sidecar
    parsed_contents = self.parse_sidecar_lua(decoded_contents)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.koreader.action", line 345, in parse_sidecar_lua
    for bookmark in decoded_lua['bookmarks'].values()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
```

**Comment by kyxap** [comment]
@andreaschari  are you suing wired or wireless sync method?

**Comment by andreaschari** [comment]
Wired but I haven't been able to reproduce it since.

**Comment by kyxap** [comment]
so no issue that this point?

**Comment by andreaschari** [comment]
Yes seems to be OK now

**Comment by kyxap** [comment]
ok! gonna close it, let me know if this will happen again or find anything else
