### ISSUE TITLE
FYI: Sync Calibre to KOReader is broken and disabled as of now

### ISSUE THREAD

**Issue by kyxap** [kyxap/koreader-calibre-plugin#8]
Hi all,

<img width="307" alt="image" src="https://github.com/user-attachments/assets/27242a47-135b-430a-94f1-987997c6e170">

The feature is broken at this moment and I'm not sure if I there anyone who is using it. So please let me know if it's needed! And I will try to fix it as well. As of now I will disable UI element to avoid any frustration. 

Current issue on windows:

1) If running in non debug mode:
```bash
calibre, version 7.15.0
ERROR: Unhandled exception: <b>PermissionError</b>:[WinError 5] Access is denied: 'Utopia of Rules_ On Technology, Stupidity, and the Secret Joys of Bureaucracy, The - David Graeber &amp; Devid Griebier.sdr'

calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Extract ISBN (1, 6, 3) && Goodreads (1, 8, 2) && Goodreads Sync (1, 16, 8) && KOReader Sync (0, 6, 2)
Traceback (most recent call last):
  File "calibre_plugins.koreader.action", line 674, in sync_missing_sidecars_to_koreader
  File "calibre_plugins.koreader.action", line 610, in push_metadata_to_koreader_sidecar
  File "os.py", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'Utopia of Rules_ On Technology, Stupidity, and the Secret Joys of Bureaucracy, The - David Graeber & Devid Griebier.sdr'
```

2) If running calibre in debug (e.g. terminal pwd is in Downloads)
<img width="548" alt="image" src="https://github.com/user-attachments/assets/91c15622-c57c-47b2-905f-d80b3be2e6a0">

Sidecars will be dowaloded locally in that folder:

But UI going to show that all sidecar is missing
<img width="380" alt="image" src="https://github.com/user-attachments/assets/cef98d01-8a60-4f0e-8ef8-5dab4639e4fe">

```bash
calibre, version 7.15.0
Success: 6 books on device without sidecars.
Sidecar creation succeeded for 6.
Sidecar creation failed for 0.
No attempt made for 0 (no metadata in Calibre to push).
See below for details.

  {
    "result": "success",
    "book_id": 311,
    "book_uuid": "d840bffc-c9b9-4043-8424-e4c2a4ff8854",
    "sidecar_path": "Utopiia pravil. O tiekhnologhiiakh, ghluposti i tainom obaianii biurokratii - David Graeber & Devid Griebier.sdr/metadata.epub.lua"
  }
]```

Some logic bug and some file access problem as well

**Comment by kyxap** [comment]
see https://github.com/kyxap/koreader-calibre-plugin/issues/8
